name: Build, Push, and Promote Image to Dev

on:
  workflow_dispatch:

env:
  OPENSHIFT_REGISTRY: ${{ vars.OPENSHIFT_REGISTRY }}
  OPENSHIFT_URL: ${{ vars.OPENSHIFT_URL }}
  OPENSHIFT_NAMESPACE: ${{ vars.OPENSHIFT_NAMESPACE }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  BUILD_TAG: latest
  TARGET_TAG: dev

jobs:
  build-push-promote-dev:
    name: Build, Push to Latest, and Tag Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to OpenShift Internal Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.OPENSHIFT_REGISTRY }}
          username: ${{ secrets.OPENSHIFT_USERNAME }}
          password: ${{ secrets.OPENSHIFT_PASSWORD }}

      - name: Build and Push Image (only latest)
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            -t $OPENSHIFT_REGISTRY/$OPENSHIFT_NAMESPACE/$IMAGE_NAME:$BUILD_TAG \
            .

      - name: Install oc CLI
        uses: redhat-actions/oc-installer@v1

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_URL }}
          insecure_skip_tls_verify: true
          username: ${{ secrets.OPENSHIFT_USERNAME }}
          password: ${{ secrets.OPENSHIFT_PASSWORD }}

      - name: Promote Image from latest to dev
        run: |
          oc tag $OPENSHIFT_NAMESPACE/$IMAGE_NAME:$BUILD_TAG $OPENSHIFT_NAMESPACE/$IMAGE_NAME:$TARGET_TAG
