name: Build, Push, and Promote Image to Dev

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

env:
  REGISTRY_URL: ${{ vars.REGISTRY_URL }}
  OPENSHIFT_SERVER_URL: ${{ vars.OPENSHIFT_SERVER_URL }}
  IMAGE_NAMESPACE: ${{ vars.IMAGE_NAMESPACE }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  BUILD_TAG: latest
  TARGET_TAG: dev

jobs:
  build-push-promote-dev:
    name: Build, Push to Latest, and Tag Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to OpenShift Internal Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.OPENSHIFT_USERNAME }}
          password: ${{ secrets.OPENSHIFT_PASSWORD }}

      - name: Build and Push Image (only latest)
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            -t $REGISTRY_URL/$IMAGE_NAMESPACE/$IMAGE_NAME:$BUILD_TAG \
            .

      - name: Install oc CLI
        uses: redhat-actions/oc-installer@v1

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER_URL }}
          username: ${{ secrets.OPENSHIFT_USERNAME }}
          password: ${{ secrets.OPENSHIFT_PASSWORD }}

      - name: Promote Image from latest to dev
        run: |
          oc tag $IMAGE_NAMESPACE/$IMAGE_NAME:$BUILD_TAG $IMAGE_NAMESPACE/$IMAGE_NAME:$TARGET_TAG
